#include "smart_factory/platform/alarm_service.hpp"
#include <sqlite3.h>
#include <chrono>
#include <filesystem>
#include <stdexcept>
#include <algorithm>

namespace smart_factory { namespace {
void execSql(sqlite3* db,const char* sql){char* e=nullptr;if(sqlite3_exec(db,sql,nullptr,nullptr,&e)!=SQLITE_OK){std::string m=e?e:sqlite3_errmsg(db);sqlite3_free(e);throw std::runtime_error(m);}}
std::string textCol(sqlite3_stmt* s,int c){const auto* p=reinterpret_cast<const char*>(sqlite3_column_text(s,c));return p?std::string(p):std::string();}
boost::json::object parseObj(const std::string& text){auto v=boost::json::parse(text);return v.is_object()?v.as_object():boost::json::object{};}
}
std::int64_t AlarmService::nowMs(){return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
std::string AlarmService::stringField(const boost::json::object& o,const char* k,const std::string& f){if(const auto* v=o.if_contains(k);v&&v->is_string())return std::string(v->as_string());return f;}
std::int64_t AlarmService::intField(const boost::json::object& o,const char* k,std::int64_t f){if(const auto* v=o.if_contains(k)){if(v->is_int64())return v->as_int64();if(v->is_uint64())return static_cast<std::int64_t>(v->as_uint64());}return f;}
AlarmService::AlarmService(std::string directory):directory_(std::move(directory)){std::filesystem::create_directories(directory_);databasePath_=(std::filesystem::path(directory_)/"platform-alarm-b3.sqlite3").string();if(sqlite3_open_v2(databasePath_.c_str(),&db_,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK)throw std::runtime_error("cannot open B3 alarm store");std::lock_guard l(mutex_);initializeLocked();}
AlarmService::~AlarmService(){std::lock_guard l(mutex_);if(db_)sqlite3_close(db_);}
void AlarmService::initializeLocked(){execSql(db_,"PRAGMA journal_mode=WAL;");execSql(db_,"PRAGMA synchronous=FULL;");execSql(db_,"PRAGMA busy_timeout=3000;");execSql(db_,R"SQL(
CREATE TABLE IF NOT EXISTS alarm_v2_occurrences(occurrence_id TEXT PRIMARY KEY,alarm_id TEXT NOT NULL,device_id TEXT NOT NULL,point_id TEXT NOT NULL DEFAULT '',rule_id TEXT NOT NULL DEFAULT '',rule_version TEXT NOT NULL DEFAULT '',source_domain TEXT NOT NULL,severity TEXT NOT NULL,condition_state TEXT NOT NULL,ack_state TEXT NOT NULL,raised_at INTEGER NOT NULL,normalized_at INTEGER NOT NULL DEFAULT 0,acknowledged_at INTEGER NOT NULL DEFAULT 0,acknowledged_by TEXT NOT NULL DEFAULT '',revision INTEGER NOT NULL,occurrence_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_alarm_v2_alarm ON alarm_v2_occurrences(alarm_id,raised_at);
CREATE TABLE IF NOT EXISTS alarm_v2_events(event_id TEXT PRIMARY KEY,occurrence_id TEXT NOT NULL,event_type TEXT NOT NULL,timestamp INTEGER NOT NULL,revision INTEGER NOT NULL,event_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_alarm_v2_events_time ON alarm_v2_events(timestamp);
CREATE TABLE IF NOT EXISTS alarm_v2_outbox(event_id TEXT PRIMARY KEY,object_id TEXT NOT NULL,object_revision INTEGER NOT NULL,payload_json TEXT NOT NULL,created_at INTEGER NOT NULL,published INTEGER NOT NULL DEFAULT 0);
)SQL");}
std::string AlarmService::latestOpenOccurrenceIdLocked(const std::string& alarmId) const{sqlite3_stmt* s=nullptr;sqlite3_prepare_v2(db_,"SELECT occurrence_id FROM alarm_v2_occurrences WHERE alarm_id=?1 AND condition_state!='NORMAL' ORDER BY raised_at DESC LIMIT 1;",-1,&s,nullptr);sqlite3_bind_text(s,1,alarmId.c_str(),-1,SQLITE_TRANSIENT);std::string id;if(sqlite3_step(s)==SQLITE_ROW)id=textCol(s,0);sqlite3_finalize(s);return id;}
boost::json::object AlarmService::readOccurrenceLocked(const std::string& id) const{sqlite3_stmt* s=nullptr;sqlite3_prepare_v2(db_,"SELECT occurrence_json FROM alarm_v2_occurrences WHERE occurrence_id=?1;",-1,&s,nullptr);sqlite3_bind_text(s,1,id.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)!=SQLITE_ROW){sqlite3_finalize(s);throw std::runtime_error("alarm occurrence not found");}auto o=parseObj(textCol(s,0));sqlite3_finalize(s);return o;}
void AlarmService::appendEventAndOutboxLocked(const boost::json::object& occ,const std::string& type,const std::string& actor,const std::string& comment){const auto ts=nowMs();const auto id=stringField(occ,"occurrenceId");const auto rev=intField(occ,"revision",1);const auto eid=id+":"+type+":"+std::to_string(rev)+":"+std::to_string(ts);boost::json::object ev{{"eventId",eid},{"occurrenceId",id},{"alarmId",stringField(occ,"alarmId")},{"eventType",type},{"timestamp",ts},{"revision",rev},{"conditionState",stringField(occ,"conditionState")},{"ackState",stringField(occ,"ackState")},{"sourceDomain",stringField(occ,"sourceDomain")}};if(!actor.empty())ev["actor"]=actor;if(!comment.empty())ev["comment"]=comment;const auto text=boost::json::serialize(ev);sqlite3_stmt* s=nullptr;sqlite3_prepare_v2(db_,"INSERT INTO alarm_v2_events(event_id,occurrence_id,event_type,timestamp,revision,event_json) VALUES(?1,?2,?3,?4,?5,?6);",-1,&s,nullptr);sqlite3_bind_text(s,1,eid.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,type.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,4,ts);sqlite3_bind_int64(s,5,rev);sqlite3_bind_text(s,6,text.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);throw std::runtime_error(sqlite3_errmsg(db_));}sqlite3_finalize(s);sqlite3_prepare_v2(db_,"INSERT INTO alarm_v2_outbox(event_id,object_id,object_revision,payload_json,created_at,published) VALUES(?1,?2,?3,?4,?5,0);",-1,&s,nullptr);sqlite3_bind_text(s,1,eid.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,3,rev);sqlite3_bind_text(s,4,text.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,5,ts);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);throw std::runtime_error(sqlite3_errmsg(db_));}sqlite3_finalize(s);}
boost::json::object AlarmService::upsertConditionLocked(const boost::json::object& event){const auto alarmId=stringField(event,"alarmId");const auto condition=stringField(event,"conditionState","NORMAL");if(alarmId.empty())throw std::runtime_error("alarmId required");auto occurrenceId=latestOpenOccurrenceIdLocked(alarmId);boost::json::object occ;bool created=false;if(occurrenceId.empty()&&condition!="NORMAL"){const auto raised=intField(event,"timestamp",nowMs());occurrenceId="occ:"+alarmId+":"+std::to_string(raised);occ={{"occurrenceId",occurrenceId},{"alarmId",alarmId},{"deviceId",stringField(event,"deviceId")},{"pointId",stringField(event,"pointId")},{"ruleId",stringField(event,"ruleId")},{"ruleVersion",stringField(event,"ruleVersion")},{"sourceDomain",stringField(event,"sourceDomain","UNKNOWN")},{"severity",stringField(event,"severity","WARNING")},{"conditionState",condition},{"ackState","UNACKNOWLEDGED"},{"raisedAt",raised},{"normalizedAt",0},{"acknowledgedAt",0},{"acknowledgedBy",""},{"revision",1},{"title",stringField(event,"title",alarmId)},{"message",stringField(event,"message")}};created=true;}else if(!occurrenceId.empty()){occ=readOccurrenceLocked(occurrenceId);const auto old=stringField(occ,"conditionState");if(old==condition)return occ;occ["conditionState"]=condition;occ["revision"]=intField(occ,"revision",1)+1;if(condition=="NORMAL")occ["normalizedAt"]=intField(event,"timestamp",nowMs());}else{return {};}
  const auto payload=boost::json::serialize(occ);sqlite3_stmt* s=nullptr;sqlite3_prepare_v2(db_,R"SQL(INSERT INTO alarm_v2_occurrences(occurrence_id,alarm_id,device_id,point_id,rule_id,rule_version,source_domain,severity,condition_state,ack_state,raised_at,normalized_at,acknowledged_at,acknowledged_by,revision,occurrence_json) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16) ON CONFLICT(occurrence_id) DO UPDATE SET condition_state=excluded.condition_state,normalized_at=excluded.normalized_at,revision=excluded.revision,occurrence_json=excluded.occurrence_json; )SQL",-1,&s,nullptr);sqlite3_bind_text(s,1,occurrenceId.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,alarmId.c_str(),-1,SQLITE_TRANSIENT);auto bind=[&](int i,const char* k){const auto x=stringField(occ,k);sqlite3_bind_text(s,i,x.c_str(),-1,SQLITE_TRANSIENT);};bind(3,"deviceId");bind(4,"pointId");bind(5,"ruleId");bind(6,"ruleVersion");bind(7,"sourceDomain");bind(8,"severity");bind(9,"conditionState");bind(10,"ackState");sqlite3_bind_int64(s,11,intField(occ,"raisedAt"));sqlite3_bind_int64(s,12,intField(occ,"normalizedAt"));sqlite3_bind_int64(s,13,intField(occ,"acknowledgedAt"));bind(14,"acknowledgedBy");sqlite3_bind_int64(s,15,intField(occ,"revision",1));sqlite3_bind_text(s,16,payload.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);throw std::runtime_error(sqlite3_errmsg(db_));}sqlite3_finalize(s);appendEventAndOutboxLocked(occ,created?"RAISED":condition=="NORMAL"?"RETURN_TO_NORMAL":condition=="UNKNOWN"?"CONDITION_UNKNOWN":"CONDITION_ACTIVE");return occ;}
boost::json::object AlarmService::observe(const boost::json::object& event){std::lock_guard l(mutex_);execSql(db_,"BEGIN IMMEDIATE;");try{auto o=upsertConditionLocked(event);execSql(db_,"COMMIT;");return o;}catch(...){sqlite3_exec(db_,"ROLLBACK;",nullptr,nullptr,nullptr);throw;}}
boost::json::object AlarmService::syncLegacyAlarm(const boost::json::object& a){boost::json::object e{{"alarmId",stringField(a,"id")},{"deviceId",stringField(a,"deviceId")},{"sourceDomain",stringField(a,"sourceDomain","FIELD")},{"severity",stringField(a,"severity","WARNING")},{"title",stringField(a,"title")},{"message",stringField(a,"message")},{"timestamp",intField(a,"clearedAt",intField(a,"raisedAt",nowMs()))},{"conditionState",stringField(a,"state")=="CLEARED"?"NORMAL":"ACTIVE"}};auto o=observe(e);if(const auto ack=intField(a,"acknowledgedAt",0);ack>0&&!o.empty()){SecurityContext actor;actor.principal.id=stringField(a,"acknowledgedBy","legacy");actor.principal.authenticated=true;try{return acknowledge(stringField(o,"occurrenceId"),actor,stringField(a,"acknowledgementComment"));}catch(...){}}return o;}
boost::json::object AlarmService::acknowledge(const std::string& id,const SecurityContext& actor,const std::string& comment){std::lock_guard l(mutex_);execSql(db_,"BEGIN IMMEDIATE;");try{auto occ=readOccurrenceLocked(id);if(stringField(occ,"ackState")=="ACKNOWLEDGED"){execSql(db_,"COMMIT;");return occ;}occ["ackState"]="ACKNOWLEDGED";occ["acknowledgedAt"]=nowMs();occ["acknowledgedBy"]=actor.principal.id;occ["revision"]=intField(occ,"revision",1)+1;if(!comment.empty())occ["acknowledgementComment"]=comment;const auto text=boost::json::serialize(occ);sqlite3_stmt* s=nullptr;sqlite3_prepare_v2(db_,"UPDATE alarm_v2_occurrences SET ack_state='ACKNOWLEDGED',acknowledged_at=?2,acknowledged_by=?3,revision=?4,occurrence_json=?5 WHERE occurrence_id=?1;",-1,&s,nullptr);sqlite3_bind_text(s,1,id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,2,intField(occ,"acknowledgedAt"));sqlite3_bind_text(s,3,actor.principal.id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,4,intField(occ,"revision"));sqlite3_bind_text(s,5,text.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);throw std::runtime_error(sqlite3_errmsg(db_));}sqlite3_finalize(s);appendEventAndOutboxLocked(occ,"ACKNOWLEDGED",actor.principal.id,comment);execSql(db_,"COMMIT;");return occ;}catch(...){sqlite3_exec(db_,"ROLLBACK;",nullptr,nullptr,nullptr);throw;}}
boost::json::array AlarmService::occurrences(const std::string& deviceId,const std::string& sourceDomain) const{std::lock_guard l(mutex_);sqlite3_stmt* s=nullptr;sqlite3_prepare_v2(db_,"SELECT occurrence_json FROM alarm_v2_occurrences ORDER BY raised_at DESC;",-1,&s,nullptr);boost::json::array out;while(sqlite3_step(s)==SQLITE_ROW){auto o=parseObj(textCol(s,0));if(!deviceId.empty()&&stringField(o,"deviceId")!=deviceId)continue;if(!sourceDomain.empty()&&stringField(o,"sourceDomain")!=sourceDomain)continue;out.emplace_back(std::move(o));}sqlite3_finalize(s);return out;}
std::optional<boost::json::object> AlarmService::occurrence(const std::string& id) const{std::lock_guard l(mutex_);try{return readOccurrenceLocked(id);}catch(...){return std::nullopt;}}
boost::json::array AlarmService::currentRuleProjections() const{auto all=occurrences({},"RULE");std::unordered_map<std::string,boost::json::object> latest;for(const auto& v:all){auto o=v.as_object();const auto id=stringField(o,"alarmId");if(!latest.contains(id))latest[id]=std::move(o);}boost::json::array out;for(auto& [id,o]:latest){const auto cond=stringField(o,"conditionState"),ack=stringField(o,"ackState");boost::json::object a{{"id",id},{"occurrenceId",stringField(o,"occurrenceId")},{"deviceId",stringField(o,"deviceId")},{"title",stringField(o,"title",id)},{"message",stringField(o,"message")},{"severity",stringField(o,"severity","WARNING")},{"sourceDomain","RULE"},{"raisedAt",intField(o,"raisedAt")}};a["state"]=cond=="NORMAL"?"CLEARED":ack=="ACKNOWLEDGED"?"ACKNOWLEDGED":"ACTIVE";if(intField(o,"normalizedAt")>0)a["clearedAt"]=intField(o,"normalizedAt");if(intField(o,"acknowledgedAt")>0){a["acknowledgedAt"]=intField(o,"acknowledgedAt");a["acknowledgedBy"]=stringField(o,"acknowledgedBy");}out.emplace_back(std::move(a));}return out;}
boost::json::array AlarmService::events(std::int64_t fromTs,std::int64_t toTs) const{std::lock_guard l(mutex_);sqlite3_stmt* s=nullptr;sqlite3_prepare_v2(db_,"SELECT event_json FROM alarm_v2_events WHERE timestamp>=?1 AND timestamp<=?2 ORDER BY timestamp ASC;",-1,&s,nullptr);sqlite3_bind_int64(s,1,fromTs);sqlite3_bind_int64(s,2,toTs);boost::json::array out;while(sqlite3_step(s)==SQLITE_ROW)out.emplace_back(parseObj(textCol(s,0)));sqlite3_finalize(s);return out;}
}  // namespace smart_factory
