#include "smart_factory/platform/report_service.hpp"
#include <sqlite3.h>
#include <chrono>
#include <filesystem>
#include <stdexcept>
namespace smart_factory {
namespace {std::string text(sqlite3_stmt*s,int c){const auto*p=reinterpret_cast<const char*>(sqlite3_column_text(s,c));return p?std::string(p):std::string();}}
std::int64_t ReportService::nowMs(){return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
ReportService::ReportService(std::string d):directory_(std::move(d)){std::filesystem::create_directories(directory_);path_=(std::filesystem::path(directory_)/"platform-reports.sqlite3").string();if(sqlite3_open_v2(path_.c_str(),&db_,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK)throw std::runtime_error("cannot open report store");init();}
ReportService::~ReportService(){std::lock_guard l(mutex_);if(db_)sqlite3_close(db_);}
void ReportService::init(){std::lock_guard l(mutex_);const char*sql="PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS report_jobs(job_id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,status TEXT NOT NULL,parameters_json TEXT NOT NULL,summary_json TEXT NOT NULL,html TEXT NOT NULL,csv TEXT NOT NULL);";char*e=nullptr;if(sqlite3_exec(db_,sql,nullptr,nullptr,&e)!=SQLITE_OK){std::string m=e?e:"report init failed";sqlite3_free(e);throw std::runtime_error(m);}}
std::string ReportService::csvCell(std::string v){if(!v.empty()&&(v[0]=='='||v[0]=='+'||v[0]=='-'||v[0]=='@'))v="'"+v;bool q=v.find_first_of(",\"\r\n")!=std::string::npos;std::string o;for(char c:v){if(c=='\"')o+="\"\"";else o+=c;}return q?"\""+o+"\"":o;}
boost::json::object ReportService::saveCompleted(const boost::json::object&p,const boost::json::object&s,const std::string&html,const std::string&csv){if(html.size()+csv.size()>2*1024*1024)throw std::runtime_error("report output exceeds 2 MiB limit");const auto id="report-"+std::to_string(nowMs());const auto created=nowMs();std::lock_guard l(mutex_);sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"INSERT INTO report_jobs VALUES(?1,?2,'COMPLETED',?3,?4,?5,?6);",-1,&st,nullptr);const auto pj=boost::json::serialize(p),sj=boost::json::serialize(s);sqlite3_bind_text(st,1,id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(st,2,created);sqlite3_bind_text(st,3,pj.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,4,sj.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,5,html.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,6,csv.c_str(),-1,SQLITE_TRANSIENT);const auto rc=sqlite3_step(st);sqlite3_finalize(st);if(rc!=SQLITE_DONE)throw std::runtime_error(sqlite3_errmsg(db_));return {{"jobId",id},{"status","COMPLETED"},{"createdAt",created},{"parameters",p},{"summary",s},{"html",html},{"csv",csv}};}
boost::json::object ReportService::get(const std::string&id)const{std::lock_guard l(mutex_);sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"SELECT created_at,status,parameters_json,summary_json,html,csv FROM report_jobs WHERE job_id=?1;",-1,&st,nullptr);sqlite3_bind_text(st,1,id.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(st)!=SQLITE_ROW){sqlite3_finalize(st);throw std::runtime_error("report job not found");}auto p=boost::json::parse(text(st,2)),s=boost::json::parse(text(st,3));boost::json::object o{{"jobId",id},{"createdAt",sqlite3_column_int64(st,0)},{"status",text(st,1)},{"parameters",p},{"summary",s},{"html",text(st,4)},{"csv",text(st,5)}};sqlite3_finalize(st);return o;}
}
