import{applyCommandEvent,applyFreshness,type Command,type DashboardSnapshot}from'@smart-factory/domain';
export type ResilienceCheckStatus='PASS'|'FAIL'|'BLOCKED';
export interface ResilienceCheckResult{id:string;name:string;status:ResilienceCheckStatus;detail:string;durationMs:number;}
function clone<T>(v:T):T{return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v)) as T;}
function oneCommand(snapshot:DashboardSnapshot):Command{const existing=snapshot.commands[0];if(existing)return clone(existing);const now=Date.now();return{id:'selftest-command',deviceId:snapshot.devices[0]?.id??'demo-device',action:'device.selfTest',state:'ISSUED',issuedAt:now,updatedAt:now};}
export async function runSafeResilienceSelfTests(snapshot:DashboardSnapshot):Promise<ResilienceCheckResult[]>{
 const results:ResilienceCheckResult[]=[];const run=(id:string,name:string,fn:()=>string)=>{const s=performance.now();try{results.push({id,name,status:'PASS',detail:fn(),durationMs:Math.round((performance.now()-s)*1000)/1000});}catch(e){results.push({id,name,status:'FAIL',detail:e instanceof Error?e.message:String(e),durationMs:Math.round((performance.now()-s)*1000)/1000});}};
 run('freshness-stale','数据陈旧降级',()=>{const d=clone(snapshot);const now=Date.now();d.telemetry=d.telemetry.map(t=>({...t,sampleTs:now-20_000,receiveTs:now-20_000,quality:'GOOD'}));const out=applyFreshness(d,now,{staleAfterMs:10_000,badAfterMs:60_000});if(out.telemetry.some(t=>t.quality!=='STALE'))throw new Error('expected STALE');return 'GOOD 数据在超过 staleAfterMs 后全部降为 STALE。';});
 run('freshness-bad','长期无数据判 BAD',()=>{const d=clone(snapshot);const now=Date.now();d.telemetry=d.telemetry.map(t=>({...t,sampleTs:now-70_000,receiveTs:now-70_000,quality:'GOOD'}));const out=applyFreshness(d,now,{staleAfterMs:10_000,badAfterMs:60_000});if(out.telemetry.some(t=>t.quality!=='BAD'))throw new Error('expected BAD');return '超过 badAfterMs 后数据被标记 BAD，不继续伪装实时。';});
 run('duplicate-ack','重复 ACK 幂等',()=>{let c=oneCommand(snapshot);const first=applyCommandEvent(c,{commandId:c.id,state:'RECEIVED',timestamp:Date.now(),seq:1});if(!first.accepted)throw new Error('first ACK rejected');c=first.command;const second=applyCommandEvent(c,{commandId:c.id,state:'RECEIVED',timestamp:Date.now()+1,seq:1});if(!second.accepted||!second.duplicate)throw new Error('duplicate ACK not ignored');return '同 sequence + 同状态重复事件被识别为 duplicate。';});
 run('out-of-order-ack','乱序 ACK 拒绝',()=>{let c=oneCommand(snapshot);const accepted=applyCommandEvent(c,{commandId:c.id,state:'ACCEPTED',timestamp:Date.now(),seq:2});if(!accepted.accepted)throw new Error('ACCEPTED rejected');c=accepted.command;const late=applyCommandEvent(c,{commandId:c.id,state:'RECEIVED',timestamp:Date.now()+1,seq:1});if(late.accepted)throw new Error('out-of-order event applied');return '较旧 sequence 的状态事件不会倒退命令状态。';});
 return results;
}
