<script setup lang="ts">
import{computed,onMounted,onUnmounted,ref}from'vue';
import{BRIDGE_PROTOCOL_VERSION,WEB_APP_VERSION,type BridgeHandshake,type BackendRuntimeStatus}from'@smart-factory/contracts';
import type{NativeDiscoveryStatus}from'@smart-factory/platform';
import{platform}from'../platform';import{loadRuntimeConfig}from'../runtime-config';import{useSiteStore}from'../stores/site';import PageHeader from'../components/PageHeader.vue';import StatusPill from'../components/StatusPill.vue';
const site=useSiteStore();const loading=ref(true);const base=ref<Record<string,unknown>>({});const error=ref<string|null>(null);const backendRuntime=ref<BackendRuntimeStatus|null>(null);const nativeEventCount=ref(0);const lastNativeEvent=ref<unknown>(null);let unsubscribe:(()=>void)|null=null;
const snapshot=computed(()=>({...base.value,dataLayer:{sourceMode:site.sourceMode,activeSource:site.dataSource,realtimeState:site.realtimeState,realtimeDiagnostics:site.realtimeDiagnostics,lastRealtimeError:site.lastRealtimeError},nativeEvents:{count:nativeEventCount.value,last:lastNativeEvent.value}}));
function rtTone():'good'|'warn'|'muted'{if(!backendRuntime.value)return'muted';return backendRuntime.value.realtimeEnabled&&backendRuntime.value.realtimeGranted?'good':backendRuntime.value.realtimeEnabled?'warn':'muted';}
onMounted(async()=>{unsubscribe=platform.onNativeEvent(event=>{nativeEventCount.value+=1;lastNativeEvent.value=event;});try{const[platformType,runtime,device,network,capabilities,health,config]=await Promise.all([platform.getPlatform(),platform.getRuntimeInfo(),platform.getDeviceInfo(),platform.getNetworkStatus(),platform.getCapabilities(),platform.health(),loadRuntimeConfig()]);let handshake:BridgeHandshake|null=null;let softbusStatus:NativeDiscoveryStatus|null=null;if(capabilities.includes('native.invoke')){try{handshake=await platform.invokeNativeCapability<BridgeHandshake>('bridge.handshake',{});}catch{handshake=null;}}if(capabilities.includes('softbus.discovery')){try{softbusStatus=await platform.invokeNativeCapability<NativeDiscoveryStatus>('softbus.status',{});}catch{softbusStatus=null;}}try{backendRuntime.value=await site.getRuntimeStatus();}catch{backendRuntime.value=null;}base.value={platform:platformType,runtime,device,network,capabilities,health,native:{handshake,softbusStatus},deployment:config.deployment,versions:{webVersion:WEB_APP_VERSION,shellVersion:handshake?.shellVersion??null,bridgeVersion:BRIDGE_PROTOCOL_VERSION,backendApiVersion:config.backendApiVersion,backendServiceVersion:backendRuntime.value?.backendVersion??null}};}catch(cause){error.value=cause instanceof Error?cause.message:String(cause);}finally{loading.value=false;}});onUnmounted(()=>unsubscribe?.());
</script>
<template><section class="operator-page"><PageHeader title="系统维护" eyebrow="系统管理" description="查看运行环境、实时调度、设备接入和网络状态。"/>
  <section class="engineering-tools-strip"><RouterLink to="/native">原生接口</RouterLink><RouterLink to="/compatibility">系统适配</RouterLink><RouterLink to="/resilience">恢复管理</RouterLink><RouterLink to="/benchmark">性能监测</RouterLink></section>
  <p v-if="loading" class="system-loading">正在读取系统状态…</p><p v-else-if="error" class="error">{{error}}</p>
  <template v-else>
    <div class="runtime-environment-grid">
      <section class="hmi-panel runtime-card"><div class="hmi-panel-head"><div><span>实时调度</span><h2>高优先级执行</h2></div><StatusPill :tone="rtTone()" :label="backendRuntime?.realtimeEnabled?(backendRuntime?.realtimeGranted?'可用':'受限'):'未启用'"/></div><dl class="faceplate-kv"><div><dt>启用状态</dt><dd>{{backendRuntime?.realtimeEnabled?'已启用':'未启用'}}</dd></div><div><dt>系统授权</dt><dd>{{backendRuntime?.realtimeGranted?'已授权':'未授权'}}</dd></div><div><dt>系统接口</dt><dd>{{backendRuntime?.osAdapter??'—'}}</dd></div><div><dt>状态详情</dt><dd>{{backendRuntime?.realtimeDetail??'—'}}</dd></div></dl></section>
      <section class="hmi-panel runtime-card"><div class="hmi-panel-head"><div><span>平台服务</span><h2>后端与设备接入</h2></div><StatusPill :tone="backendRuntime?'good':'muted'" :label="backendRuntime?'在线':'未知'"/></div><dl class="faceplate-kv"><div><dt>后端服务</dt><dd>{{backendRuntime?.backend??'—'}}</dd></div><div><dt>版本</dt><dd>{{backendRuntime?.backendVersion??'—'}}</dd></div><div><dt>运行模式</dt><dd>{{backendRuntime?.mode??'—'}}</dd></div><div><dt>设备接入</dt><dd>{{backendRuntime?.deviceAdapter??'—'}}</dd></div><div><dt>接入状态</dt><dd>{{backendRuntime?.deviceAdapterState??'—'}}</dd></div><div><dt>设备数量</dt><dd>{{backendRuntime?.configuredDeviceCount??'—'}}</dd></div></dl></section>
      <section class="hmi-panel runtime-card"><div class="hmi-panel-head"><div><span>数据连接</span><h2>网络与实时数据</h2></div><StatusPill :tone="site.realtimeState==='CONNECTED'?'live':'warn'" :label="site.realtimeState==='CONNECTED'?'正常':'异常'"/></div><dl class="faceplate-kv"><div><dt>数据来源</dt><dd>{{site.dataOriginLabel}}</dd></div><div><dt>重连次数</dt><dd>{{site.realtimeDiagnostics.reconnectCount}}</dd></div><div><dt>数据超时</dt><dd>{{site.realtimeDiagnostics.silenceTimeoutCount}}</dd></div><div><dt>原生事件</dt><dd>{{nativeEventCount}}</dd></div></dl></section>
    </div>
    <section class="hmi-panel system-detail-panel"><div class="hmi-panel-head"><div><span>详细信息</span><h2>系统状态</h2></div><small>只读</small></div><details><summary>查看详细信息</summary><pre>{{JSON.stringify(snapshot,null,2)}}</pre></details></section>
  </template>
</section></template>
