<script setup lang="ts">
import { onMounted, ref } from 'vue';import type { ReportJobV2 } from '@smart-factory/domain';import { useSiteStore } from '../stores/site';import PageHeader from '../components/PageHeader.vue';
const store=useSiteStore();const selected=ref('');const report=ref<ReportJobV2|null>(null);const error=ref('');const loading=ref(false);
const roleLabels:Record<string,string>={ambientTemperature:'温度',ambientHumidity:'湿度',fanState:'通风状态',occupied:'人员感应',lightState:'照明状态',lightMode:'控制模式',gasConcentration:'气体浓度',obstacleDistance:'障碍距离',motionState:'车辆状态',speed:'速度',position:'位置',task:'当前任务',totalCount:'累计计数',countRate:'当前速率',target:'目标值'};
onMounted(async()=>{await store.refreshPlatformConfig().catch(()=>{});selected.value=store.applicationInstances[0]?.instanceId??'';});
async function generate(){if(!selected.value)return;loading.value=true;error.value='';try{const to=Date.now(),from=to-60*60*1000;report.value=await store.createReportJobV2({instanceId:selected.value,from,to,format:'HTML_CSV'});}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
function download(kind:'html'|'csv'){if(!report.value)return;const content=report.value[kind],blob=new Blob([content],{type:kind==='html'?'text/html;charset=utf-8':'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${report.value.jobId}.${kind}`;a.click();URL.revokeObjectURL(a.href);}
</script>
<template><section class="operator-page report-page"><PageHeader title="运行报告" eyebrow="运行统计" description="查看指定监测应用的报警、数据完整率和操作状态，并导出运行记录。"/><section class="report-toolbar"><label>监测应用<select v-model="selected"><option v-for="i in store.applicationInstances" :key="i.instanceId" :value="i.instanceId">{{i.displayName}}</option></select></label><button class="btn-primary" :disabled="loading||!selected" @click="generate">生成最近1小时报告</button><span v-if="error" class="inline-alert" data-state="bad">{{error}}</span></section><section v-if="report" class="hmi-panel report-result"><div class="hmi-panel-head"><div><span>运行统计</span><h2>{{report.summary.displayName}}</h2></div><small>截至 {{new Date(report.summary.dataCutoff).toLocaleString('zh-CN',{hour12:false})}}</small></div><div class="overview-kpi-grid"><div><span>报警发生</span><strong>{{report.summary.alarmOccurrences}}</strong></div><div><span>未确认</span><strong>{{report.summary.unacknowledgedOccurrences}}</strong></div><div><span>结果待确认</span><strong>{{report.summary.unresolvedCommands}}</strong></div><div><span>配置版本</span><strong>{{report.summary.configRevision}}</strong></div></div><div class="table-wrap"><table class="hmi-table"><thead><tr><th>监测项目</th><th>测点</th><th>收到 / 应收</th><th>数据完整率</th></tr></thead><tbody><tr v-for="p in report.summary.points" :key="p.role"><td>{{roleLabels[p.role]??p.role}}</td><td>{{p.deviceId}} · {{p.pointId}}</td><td>{{p.coverage.receivedSamples}} / {{p.coverage.expectedSamples}}</td><td>{{p.coverage.coverage===null?'—':`${(p.coverage.coverage*100).toFixed(1)}%`}}</td></tr></tbody></table></div><div class="report-actions"><button class="btn-secondary" @click="download('html')">导出网页报告</button><button class="btn-secondary" @click="download('csv')">导出表格</button></div></section></section></template>
